# Generated by Django 2.2.6 on 2019-10-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='serach',
            new_name='search',
        ),
    ]
